version: "3"
services:
  db:
    image: "postgres@sha256:3a82e1f56c8f0f5616a11103ac3d47e632c3938698946a7ad26da0df1334744a"
    container_name: koremina_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_dev:/var/lib/postgresql/data
