version: "3"
services:
  db:
    image: "postgres@sha256:a9abf4275f9e99bff8e6aed712b3b7dfec9cac1341bba01c1ffdfce9ff9fc34a"
    container_name: koremina_dev
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes:
      - ./postgres_dev:/var/lib/postgresql/data
