version: "3"
services:
  db:
    image: "postgres"
    container_name: koremina_dev
    ports:
    - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
    volumes: 
      - ./postgres_dev:/var/lib/postgresql/data